### ISSUE TITLE
Unable to process map with value type of list

### ISSUE THREAD

**Issue by hangxie** [hangxie/parquet-tools#170]
With parquet file generated by parquet-go's json_schema.go example:

```
$ parquet-tools schema json_schema.parquet
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/alecthomas/kong.catch(0x1400081fe60)
	github.com/alecthomas/kong@v0.2.16/kong.go:383 +0xb8
panic({0x103c7e2c0, 0x140000cd260})
	runtime/panic.go:838 +0x204
github.com/hangxie/parquet-tools/cmd.(*schemaNode).updateTagFromConvertedType(0x1400081ec48, 0x1400060ef60?)
	github.com/hangxie/parquet-tools/cmd/schema.go:210 +0x818
github.com/hangxie/parquet-tools/cmd.(*schemaNode).getTagMap(0x1400081ec48)
	github.com/hangxie/parquet-tools/cmd/schema.go:285 +0x520
github.com/hangxie/parquet-tools/cmd.getTagMapAsChild({0x0, 0x0, 0x140000ca960, {0x140006143da, 0x5}, 0x140000ca9b0, 0x140000ca9b8, 0x0, 0x0, 0x0, ...}, ...)
	github.com/hangxie/parquet-tools/cmd/schema.go:312 +0x98
github.com/hangxie/parquet-tools/cmd.(*schemaNode).updateTagFromConvertedType(0x1400014ecb0, 0x1400060eed0?)
	github.com/hangxie/parquet-tools/cmd/schema.go:225 +0x558
github.com/hangxie/parquet-tools/cmd.(*schemaNode).getTagMap(0x1400014ecb0)
	github.com/hangxie/parquet-tools/cmd/schema.go:285 +0x520
github.com/hangxie/parquet-tools/cmd.(*schemaNode).jsonSchema(0x1400014ecb0)
	github.com/hangxie/parquet-tools/cmd/schema.go:129 +0x24
github.com/hangxie/parquet-tools/cmd.(*schemaNode).jsonSchema(0x1400014e7e0)
	github.com/hangxie/parquet-tools/cmd/schema.go:147 +0x160
github.com/hangxie/parquet-tools/cmd.(*SchemaCmd).Run(0x104375920, 0x1?)
	github.com/hangxie/parquet-tools/cmd/schema.go:37 +0x278
reflect.Value.call({0x103b79460?, 0x104375920?, 0x140006bfad8?}, {0x1038feff2, 0x4}, {0x1400000e1b0, 0x1, 0x10314604c?})
	reflect/value.go:556 +0x5e4
reflect.Value.Call({0x103b79460?, 0x104375920?, 0xc?}, {0x1400000e1b0, 0x1, 0x1})
	reflect/value.go:339 +0x98
github.com/alecthomas/kong.callMethod({0x1038feb24, 0x3}, {0x103c05580?, 0x104375920?, 0x3?}, {0x103b79460?, 0x104375920?, 0x0?}, 0x0?)
	github.com/alecthomas/kong@v0.2.16/callbacks.go:71 +0x3a4
github.com/alecthomas/kong.(*Context).RunNode(0x140000c4f80, 0x1400038e700, {0x140006bff00, 0x1, 0x1})
	github.com/alecthomas/kong@v0.2.16/context.go:706 +0x468
github.com/alecthomas/kong.(*Context).Run(0x1400038e1c0?, {0x140006bff00?, 0x0?, 0x0?})
	github.com/alecthomas/kong@v0.2.16/context.go:723 +0xc0
main.main()
	github.com/hangxie/parquet-tools/main.go:40 +0x2bc
```

**Comment by hangxie** [comment]
Addressed by https://github.com/hangxie/parquet-tools/pull/171
